version: "3.8"

services:
  pets-service:
    build:
      context: ./services/pets-service
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
